### PR TITLE
Adding ContentsForHomePage and OsloDinerReviews

### PR DESCRIPTION
**Pull request by Beatrice1d**
image
image
image
image

### CODE REVIEW

**Comment by Emex4gman** [comment]
pls feche the new updates b4 creating a pull request

**Comment by Emex4gman** [comment]
and send the github page link or your forked repo

**Comment by Beatrice1d** [comment]
https://github.com/Cramwordplay/oslodiner.git

**Comment by Beatrice1d** [comment]
That's my forked repo

**Comment by Emex4gman** [comment]
ahh you ur repo is 51 commits behind Oslo-Diner:master and a lot of upadates have been done

**Comment by Beatrice1d** [comment]
https://github.com/Cramwordplay/oslodiner/tree/ContentsForPages

This is the githublink

**Comment by Beatrice1d** [comment]
Okay so what can I do?

**Comment by Beatrice1d** [comment]
I have tried to fork it again but it keeps saying I have already forked the repo

**Comment by Emex4gman** [comment]
on ur command line run this code

`git remote add upstream https://github.com/Oslo-Diner/oslodiner.git`
`git fetch upstream`
`git rebase upstream/master`
`git push origin master --force`

**Comment by Emex4gman** [comment]
while in ur master head

**Comment by Emex4gman** [comment]
I will be cloning this

**Pull request closed without merging**
